version: 2.1
jobs:
  test:
    
    docker:
      - image: circleci/android:api-28

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: "Update Submodules"
          command: |
            git submodule init
            git submodule update --recursive
      - run: bundle install
      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git -b master
            ./flutter/bin/flutter doctor

      - run:
          name: Build App
          command: |
            ../flutter/bin/flutter test
            ../flutter/bin/flutter build apk --release --build-number=$CIRCLE_BUILD_NUM
            
workflows:
  version: 2
  build:
    jobs:
      - test